---
title: "rfid_SpatialBehavior"
output: 
  html_notebook: 
    toc: yes
    toc_depth: 5
    code_folding: hide
---

# Setup

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(data.table)
library(ggplot2)
library(RColorBrewer)
library(glmmTMB)
# library(lme4)
# library(lmerTest)
library(knitr)
my_colors <- c("dodgerblue","goldenrod","darkgray","black","tomato","purple","maroon","limegreen") 
# wd <- paste("I:/My Drive/Work/1_projects/2024_Vogt_LID_SWRDisrupt") ## laptop
# wd <- paste("H:/My Drive/Work/1_projects/2024_Vogt_LID_SWRDisrupt") ## home PC
wd <- paste("Y:/Data/FieldProject") ## ayaPC
output_fp <- paste("Y:/Data/FieldProject/Output") ## set result output fp
```

# Load data

```{r}
data <- data.table::fread(paste0(wd,"/Results/ALLTRIAL_RFID.csv")) ## this is just T005 data right now. 
# head(data)
# unique(data$zone)

## My zone layout

# ___________
# 10  11   12
# 7   8    9
# 4   5    6 
# 1   2    3
# __________

df <- data %>% 
  mutate(sex=factor(sex,levels=c("M","F"))) %>% ## reorder levels
  mutate(zone=as.factor(zone))
# df


```


# data summary

```{r}
df %>% 
  group_by(sex) %>% 
  summarize(avg_reads = n())

df2 <- df %>% 
  group_by(day,sex) %>% 
  summarize(avg_reads = n())

# Plotting the average reads by sex
ggplot(df2, aes(x = day, y = avg_reads, color = sex)) +
  geom_line() +
  geom_point() +
  labs(title = "Average RFID Reads by Sex Across Days", 
       x = "Day", 
       y = "Average RFID Reads") +
  theme_minimal()

```


```{r}
# Summarize data by zone and day
df_summary_zone <- df %>%
  group_by(day, zone) %>%
  summarize(total_reads = n()) %>%
  mutate(percentage = total_reads / sum(total_reads) * 100)

# Plotting percentage of reads by zone, faceted by day
ggplot(df_summary_zone, aes(x = factor(zone), y = percentage, fill = zone)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ day) +
  labs(title = "Percentage of RFID Reads per Zone Across Days", 
       x = "Zone", 
       y = "Percentage of Reads") +
  theme_minimal()

```



# Zone reads, lineplot visualization

```{r fig.height=2.5, fig.width=9}
ggplot(filter(df,trial=="T005"),
       aes(x=noon_time_sec/86400+1,y=factor(zone,levels=1:14),group=1)) + ## x axis day number
  geom_line(linewidth=0.5,color="red",alpha=0.5) +
  geom_point(size=0.5,color="black",na.rm=TRUE) +
  scale_x_continuous(breaks=seq(0,14,by=2),limits=c(1,13.3)) +
  scale_y_discrete(breaks=c(2,4,6,8,10,12)) + ## show specific zone labels.
  # geom_vline(xintercept=6.5,linewidth=0.5,color="red",linetype=2) +
  labs(x="Night",y="Zone") +
  theme_bw() +
  theme(
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(size=8),  # Adjust x axis label font size
    axis.text.y = element_text(size=8)   # Adjust y axis label font size
  ) +
  facet_wrap(~code,nrow=2,ncol=8)

# ggsave(paste0(output_fp,"/plot.svg"),width=2,height=2,units="in")
# ggsave(paste0(output_fp,"/T001_ZoneActivityLineplot.png"),height=2.5,width=7,units="in",dpi=300)
```
# Spatial RFID read heatmap visualization

```{r}
zone_coords <- df %>% 
  select(zone,zone_x,zone_y) %>% 
  unique() 

df2 <- df %>%
  group_by(trial,genotype,sex,code,noon_day,zone) %>%
  tally() %>%
  rename(subject_zone_reads=n) %>%
  ungroup() %>%
  mutate(zone=as.factor(zone)) %>% ## change zone to integer
  group_by(trial,genotype,sex,code) %>% # Complete for each mouse, on each day, for all zones
  tidyr::complete(noon_day=1:max(df$noon_day),zone=factor(1:12),fill=list(subject_zone_reads=0)) %>% ## expand to all days and zones
  left_join(zone_coords,by="zone") %>% ## bring back in zone_x zone_y coords
  ungroup() %>%
  group_by(code,noon_day) %>%
  mutate(subject_total_daily_sum=sum(subject_zone_reads)) %>%
  mutate(subject_daily_zone_percent=(subject_zone_reads/subject_total_daily_sum)*100) %>%
  ungroup() %>%
  group_by(trial,sex,zone,noon_day) %>%
  mutate(total_daily_zone_sex_reads=sum(subject_zone_reads)) %>%
  ungroup() %>%
  mutate(sex_competitor_percent=(subject_zone_reads/total_daily_zone_sex_reads)*100) %>% 
  mutate(sex_competitor_percent=replace(sex_competitor_percent,is.nan(sex_competitor_percent),0)) %>% ## NaN > 0s
  select(trial,genotype,sex,code,noon_day,zone,zone_x,zone_y,subject_zone_reads,everything())
  
# df2
```


```{r echo=FALSE, fig.height=5, fig.width=5}
## T005 males
ggplot(filter(df2,
              sex=="M",
              noon_day %in% 1:11),
       aes(x=zone_x,y=zone_y)) + ## x axis day number
  geom_tile(aes(fill=subject_daily_zone_percent),color="black") + ## get daily sum
  scale_fill_gradientn(colors=c("white","blue3","red2"),
                       values=scales::rescale(c(0,0.00001,1)), ## set breakpoints
                       limits=c(0,100),guide="colorbar") +
  labs(x="Night",y="",fill="% of nightly RFID reads") +
  theme(axis.title=element_text(face="bold",size=8),
        axis.text.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(), 
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        # legend.title=element_blank(),
        legend.title=element_text(angle=90),
        # legend.position="",
        strip.text=element_text(face="bold",size=8)) +
  facet_grid(code~noon_day,switch="both")

# ggsave(paste0(output_fp,"/plot.png"),height=8,width=3.5,units="in",dpi=1200)
# ggsave(paste0(output_fp,"/plot.svg"),height=2,width=2,units="in")

## T005 females
ggplot(filter(df2,
              sex=="F",
              noon_day %in% 1:11),
       aes(x=zone_x,y=zone_y)) + ## x axis day number
  geom_tile(aes(fill=subject_daily_zone_percent),color="black") + ## get daily sum
  scale_fill_gradientn(colors=c("white","blue3","red2"),
                       values=scales::rescale(c(0,0.00001,1)), ## set breakpoints
                       limits=c(0,100),guide="colorbar") +
  labs(x="Night",y="",fill="% of nightly RFID reads") +
  theme(axis.title=element_text(face="bold",size=8),
        axis.text.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(), 
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        # legend.title=element_blank(),
        legend.title=element_text(angle=90),
        # legend.position="",
        strip.text=element_text(face="bold",size=8)) +
  facet_grid(code~noon_day,switch="both")

# ggsave(paste0(output_fp,"/plot.png"),height=8,width=3.5,units="in",dpi=1200)
# ggsave(paste0(output_fp,"/plot.svg"),height=2,width=2,units="in")
```



# Territory Map Visualization

```{r}
colors <- c("white","blue","yellow","purple","green","maroon","cyan3","red","dodgerblue","orange","blue4","darkgray","black") ## AAAUnclaimed goes first

zone_coords <- df %>% 
  select(zone,zone_x,zone_y) %>% 
  unique() 
perc_ownership_threshold <- 50 ## set the percent ownership threshold here

df1 <- df %>%
  group_by(trial,genotype,sex,code,noon_day,zone) %>%
  tally() %>%
  rename(subject_zone_reads=n) %>%
  ungroup() %>%
  mutate(zone=as.factor(zone)) %>% ## change zone to integer
  group_by(trial,genotype,sex,code) %>% # Complete for each mouse, on each day, for all zones
  tidyr::complete(noon_day=1:max(df$noon_day),zone=factor(1:12),fill=list(subject_zone_reads=0)) %>% ## expand to all days and zones
  left_join(zone_coords,by="zone") %>% ## bring back in zone_x zone_y coords
  ungroup() %>%
  group_by(trial,sex,zone,noon_day) %>%
  mutate(total_daily_zone_sex_reads=sum(subject_zone_reads)) %>%
  ungroup() %>%
  mutate(sex_competitor_percent=(subject_zone_reads/total_daily_zone_sex_reads)*100) %>% 
  mutate(sex_competitor_percent=replace(sex_competitor_percent,is.nan(sex_competitor_percent),0)) %>% ## NaN > 0s
  select(trial,genotype,sex,code,noon_day,zone,zone_x,zone_y,subject_zone_reads,everything())

df2m <- df1 %>% 
  filter(sex=="M") %>% ## get males
  # filter(total_daily_zone_sex_reads>100) %>% ## optional: set minimum number of rfid reads to qualify
  filter(sex_competitor_percent>perc_ownership_threshold) %>% ## set ownership thresholds
  mutate(zone=as.integer(as.character(zone))) %>%
  mutate(zone_owner=code) %>% 
  select(trial,genotype,noon_day,zone,zone_owner) %>% 
  group_by(trial,genotype,noon_day) %>% 
  tidyr::complete(zone=1:12,fill=list(zone_owner="AAAUnclaimed")) %>% ## Complete non-captured zones with "Unclaimed"
  ungroup() %>% 
  mutate(zone=as.factor(zone)) %>% ## change back to factor
  left_join(zone_coords,by="zone") ## bring back in zone_x zone_y coords

df2f <- df1 %>% 
  filter(sex=="F") %>% ## get males
  # filter(total_daily_zone_sex_reads>100) %>% ## optional: set minimum number of rfid reads to qualify
  filter(sex_competitor_percent>perc_ownership_threshold) %>% ## set ownership threshold
  mutate(zone=as.integer(as.character(zone))) %>%
  mutate(zone_owner=code) %>% 
  select(trial,genotype,noon_day,zone,zone_owner) %>% 
  group_by(trial,genotype,noon_day) %>% 
  tidyr::complete(zone=1:12,fill=list(zone_owner="AAAUnclaimed")) %>% ## Complete non-captured zones with "Unclaimed"
  ungroup() %>% 
  mutate(zone=as.factor(zone)) %>% ## change back to factor
  left_join(zone_coords,by="zone") ## bring back in zone_x zone_y coords
  
```


```{r fig.height=2.25, fig.width=7}
## T005 males
ggplot(filter(df2m,
              trial=="T005",
              noon_day %in% 1:11),
       aes(x=zone_x,y=zone_y)) +
  geom_tile(aes(fill=factor(zone_owner)),color="black") + # Make sure zone_owner is a factor
  scale_fill_manual(values=colors) +
  labs(x="Night",y="",title="Nightly male zone majority stake",fill="") +
  theme_minimal() +
  theme(axis.title=element_text(face = "bold", size = 8),
        axis.text.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        # legend.title = element_text(angle = 90),
        legend.position="bottom",
        strip.text = element_text(face="bold",size=8)) +
  facet_grid(trial~noon_day,switch="both")

# ggsave(paste0(output_fp,"/plot.svg"),width=7,height=1.5,units="in")
```



```{r fig.height=2.25, fig.width=7}
## T005 males
ggplot(filter(df2f,
              trial=="T005",
              noon_day %in% 1:11),
       aes(x=zone_x,y=zone_y)) +
  geom_tile(aes(fill=factor(zone_owner)),color="black") + # Make sure zone_owner is a factor
  scale_fill_manual(values=colors) +
  labs(x="Night",y="",title="Nightly female zone majority stake",fill="") +
  theme_minimal() +
  theme(axis.title=element_text(face = "bold", size = 8),
        axis.text.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        # legend.title = element_text(angle = 90),
        legend.position="bottom",
        strip.text = element_text(face="bold",size=8)) +
  facet_grid(trial~noon_day,switch="both")

# ggsave(paste0(output_fp,"/plot.svg"),width=7,height=1.5,units="in")
```


